-- Tabla para días bloqueados específicos (Vacaciones, festivos, días personales)
CREATE TABLE IF NOT EXISTS public.blocked_dates (
    id bigint generated by default as identity primary key,
    date date not null unique,
    reason text default 'No disponible',
    created_at timestamp with time zone default now()
);

-- Habilitar RLS
ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;

-- Políticas
DROP POLICY IF EXISTS "Public read blocked dates" ON public.blocked_dates;
CREATE POLICY "Public read blocked dates" 
ON public.blocked_dates FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Admin manage blocked dates" ON public.blocked_dates;
CREATE POLICY "Admin manage blocked dates" 
ON public.blocked_dates FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
