-- Tabla para configuración del calendario
CREATE TABLE IF NOT EXISTS public.calendar_settings (
    id bigint generated by default as identity primary key,
    day_of_week int not null, -- 0=Domingo, 1=Lunes...
    is_work_day boolean default true,
    start_time time default '09:00',
    end_time time default '17:00',
    created_at timestamp with time zone default now()
);

-- Insertar configuración por defecto
INSERT INTO public.calendar_settings (day_of_week, is_work_day) VALUES
(1, true), (2, true), (3, true), (4, true), (5, true), -- Lunes a Viernes
(6, false), (0, false); -- Sábado y Domingo no laborales

-- Habilitar RLS
ALTER TABLE public.calendar_settings ENABLE ROW LEVEL SECURITY;

-- Política: Solo Admin puede ver/editar
CREATE POLICY "Admin access calendar" 
ON public.calendar_settings 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
