-- 1. Crear la tabla 'appointments' si no existe
CREATE TABLE IF NOT EXISTS public.appointments (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    guest_name text not null,
    guest_email text not null,
    scheduled_at timestamp with time zone not null,
    type text default 'individual',
    status text default 'pending'
);

-- 2. Habilitar seguridad (RLS)
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas de Acceso (Permisos)

-- Permitir a CUALQUIERA (público) insertar citas (Agendar)
DROP POLICY IF EXISTS "Permitir insertar a publico" ON public.appointments;
CREATE POLICY "Permitir insertar a publico" 
ON public.appointments 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Permitir leer las citas (Para el Admin y Portal)
-- Nota: En producción esto debería restringirse solo a admin, 
-- pero para este MVP lo dejamos abierto para que tu Dashboard funcione sin auth compleja.
DROP POLICY IF EXISTS "Permitir ver a todos" ON public.appointments;
CREATE POLICY "Permitir ver a todos" 
ON public.appointments 
FOR SELECT 
USING (true);
