-- SCRIPT DE CORRECCIÓN (Clean Slate)
-- Borramos la tabla de configuración antigua para recrearla correctamente con las reglas necesarias.

-- 1. Recrear Tabla Calendar Settings
DROP TABLE IF EXISTS public.calendar_settings;

CREATE TABLE public.calendar_settings (
    id bigint generated by default as identity primary key,
    day_of_week int not null unique, -- AHORA SÍ tiene la restricción UNIQUE
    is_work_day boolean default true,
    start_time text default '09:00',
    end_time text default '17:00',
    created_at timestamp with time zone default now()
);

-- Insertar valores por defecto
INSERT INTO public.calendar_settings (day_of_week, is_work_day)
VALUES 
(1, true), (2, true), (3, true), (4, true), (5, true), (6, false), (0, false);

-- Políticas de Seguridad Calendar
ALTER TABLE public.calendar_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read settings" ON public.calendar_settings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admin update settings" ON public.calendar_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- 2. Asegurar Tabla Blocked Dates
CREATE TABLE IF NOT EXISTS public.blocked_dates (
    id bigint generated by default as identity primary key,
    date date not null unique,
    reason text default 'No disponible',
    created_at timestamp with time zone default now()
);

-- Políticas de Seguridad Blocked Dates
ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;

-- Limpiar políticas viejas para evitar errores de "already exists" warning
DROP POLICY IF EXISTS "Public read blocked dates" ON public.blocked_dates;
DROP POLICY IF EXISTS "Admin manage blocked dates" ON public.blocked_dates;

CREATE POLICY "Public read blocked dates" ON public.blocked_dates FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admin manage blocked dates" ON public.blocked_dates FOR ALL TO authenticated USING (true) WITH CHECK (true);
